# Generated by Django 4.0.3 on 2022-04-06 07:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='published_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
